### ISSUE TITLE
Type annotations with `RecordDict` not satisfying mypy

### ISSUE THREAD

**Issue by alichaudry** [maxmind/MaxMind-DB-Reader-python#118]
I'm not able to figure out how to get mypy to be okay w/ the response from this library. The code I have looks something like this:

```python
def ipinfo_db_lookup(ip_address: str) -> dict | None:
    with maxminddb.open_database(ipinfo_db_path) as reader:
        record: dict | None = reader.get(ip_address)
    return record
```

This is what mypy is saying:

```python
Incompatible types in assignment (expression has type "Any | float | int | RecordList | RecordDict | None", variable has type "dict[Any, Any] | None")  [assignment]mypy(error)
```

I've even swapped `dict` for `maxminddb.types.RecordDict` and I get:

```python
Incompatible types in assignment (expression has type "Any | float | int | RecordList | RecordDict | None", variable has type "RecordDict | None")  [assignment]mypy(error)
```

Any insight would be appreciated; I don't want to have to leave a `type: ignore[assignment]` statement in here.

**Comment by oschwald** [comment]
As the return type suggests, a `get` call can return may different types depending on the particular database being used. Please see the [`mypy` documentation on type narrowing](https://mypy.readthedocs.io/en/stable/type_narrowing.html).

**Comment by alichaudry** [comment]
@oschwald I'm familiar w/ type narrowing, but the way I'm getting it to work for this looks incredibly hacky:

```python
def ipinfo_db_lookup(ip_address: str) -> dict | None:
    with maxminddb.open_database(ipinfo_db_path) as reader:
        ip_record = reader.get(ip_address)
        assert isinstance(ip_record, dict) or ip_record is None
    return ip_record
```

Is there a more graceful way of tackling this?

**Comment by oschwald** [comment]
The `mypy` documentation that I linked to provided several different approaches. I don't have any additional suggestions beyond those. For GeoIP2 or GeoLite2 databases, we provide the `geoip2` package that has structured model classes for each database type. However, it appears you are using a competitor's database, which I believe has a different internal layout.
