### ISSUE TITLE
TypeError: 'Reader' object is not iterable

### ISSUE THREAD

**Issue by rosydawn6** [maxmind/MaxMind-DB-Reader-python#124]
Hello
From the docs it suggests:
You may also iterate over the whole database. The Reader class implements the __iter__ method that returns an iterator. This iterator yields a tuple containing the network and the record.

After opening GeoIP2-ISP.mmdb and attempting to iterate over the reader I am getting
TypeError: 'Reader' object is not iterable

using maxminddb version 2.4.0

**Comment by oschwald** [comment]
We have not released that change yet. It will be in the next release.
