### ISSUE TITLE
PyPI sdist tarball no longer contains tests/data folder

### ISSUE THREAD

**Issue by frenzymadness** [maxmind/MaxMind-DB-Reader-python#132]
Hello.

I'm not sure whether this change was intentional but it's no longer possible to run tests with just the content from PyPI:

```
$ find maxminddb-2.4.0/tests/ | wc -l
52
$ find maxminddb-2.5.0/tests/ | wc -l
3
```

**Comment by frenzymadness** [comment]
And it also seems that the sdist tarball does not contain the newly bundled `libmaxminddb` folder so it's not possible to build the extension from the source.

**Comment by oschwald** [comment]
Thanks for reporting this! 2.5.1 was released with a fix.
