### ISSUE TITLE
Python aarch64/arm64 whl releases

### ISSUE THREAD

**Issue by kpark-hrp** [maxmind/MaxMind-DB-Reader-python#152]
With increasing popularity of M1/M2/M3 and ARM based cloud computing, it would be immensely helpful to also get aarch64/arm64 whl releases.

Thanks!

**Comment by oschwald** [comment]
I think we will get this automatically once `pypa/cibuildwheel` supports it. See https://github.com/pypa/cibuildwheel/issues/1746.

**Comment by kpark-hrp** [comment]
@oschwald It looks like MacOS ARM64 is now supported with this merged PR. https://github.com/pypa/cibuildwheel/pull/1700

And indicated by their README
<img width="812" alt="image" src="https://github.com/maxmind/MaxMind-DB-Reader-python/assets/122915495/b46ac62a-dd93-447d-9e24-cd96c8fa13a2">

**Comment by oschwald** [comment]
In that case, this should happen automatically in the next release.

**Comment by oschwald** [comment]
We just released 2.6.0 and it doesn't seem like they were created. Maybe we need to tweak our build matrix a bit.

**Comment by kpark-hrp** [comment]
@oschwald I think you need to add `macos-14` to the matrix. `macos-14` runs on M1, so it covers MacOS arm64.

https://github.com/maxmind/MaxMind-DB-Reader-python/blob/cc3a7090584eded9d8e3b010614ec673eb851138/.github/workflows/release.yml#L19

**Comment by oschwald** [comment]
Thanks. It [looks like you are right](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/). I had no idea that `macos-latest` meant `macos-12`. :upside_down_face:
