### ISSUE TITLE
setuptools is (incorrectly?) listed as a production dependency in pyproject.toml

### ISSUE THREAD

**Issue by lewiscollard** [maxmind/MaxMind-DB-Reader-python#154]
Hello!

The `[dependencies]` section of `pyproject.toml` [lists](https://github.com/maxmind/MaxMind-DB-Reader-python/blob/23738928bb88dab1891fe34a5ee68a6009951802/pyproject.toml#L13) `setuptools>=68.2.2`. I think this is unnecessary; it's not required in the production code, only to build it. As it is, this means that production builds must ship (or provide its own stub of) setuptools, even though it will never be used in a production deployment.

I think this should be as simple as moving the version constraint part of this dependency up to its entry in `requires` under `[build-system]`. I'd gladly open a PR for this because it seems like a trivial fix, but I do not know if there are reasons for how it currently is.

Thanks for the library!

L

**Comment by oschwald** [comment]
I think you are right. Please feel free to open a pull request.
