### ISSUE TITLE
CFFI bindings

### ISSUE THREAD

**Issue by thedrow** [maxmind/MaxMind-DB-Reader-python#16]
Under PyPy performance could be hurt by using the CPython extension.
I know that it's disabled right now but we could replace it with a CFFI extension which might boost performance.
Do you guys have a benchmark suite that you use to test this?

**Comment by oschwald** [comment]
We briefly considered using CFFI for interfacing with libmaxminddb when initially implementing it but we had some concerns about poorer performance compared to the extension with CPython. It is completely possible that these concerns are unfounded as we never did any significant testing.

There isn't a comprehensive benchmark suite, but there is a simple benchmarking script in the examples folder of this dist.

**Comment by oschwald** [comment]
I believe PyPy now has experimental support for CPython extensions. Do you know if this works? We would likely accept reasonably patches for fixes to make it work.

**Comment by thedrow** [comment]
It's been quite a while since I've tried.
I don't really need to use this library at this time.
I still think that a CFFI extension should be useful.

The cpyext compatibility layer usually works but it is slower than using CFFI due to reference counting emulation.

**Comment by oschwald** [comment]
I am closing this as I don't think we will be providing a CFFI extension in the foreseeable future.
