### ISSUE TITLE
Expose netmask

### ISSUE THREAD

**Issue by jroyalty** [maxmind/MaxMind-DB-Reader-python#18]
Any plans to expose the `netmask` field from `MMDB_lookup_result_s` in the library code?  I'm migrating over from GeoIP legacy which provided this data and I see it's not exposed in the new API.

**Comment by oschwald** [comment]
We currently don't have any particular plans, but a reasonable pull request that worked with all the modes and was tested would be accepted. If you are a paying customer, please email [support@maxmind.com](mailto:support@maxmind.com) with the feature request.

**Comment by jroyalty** [comment]
I thought of making `reader.get()` (and `Reader_get()` in the C extension) return a tuple of `(object, netmask)`.  Or perhaps a whole new method like `get_with_netmask()`.  Is there a preference?  The latter wouldn't require the GeoIP2 module to change necessarily.

**Comment by oschwald** [comment]
The latter sounds reasonable as it is a non-breaking change.

**Comment by addrians** [comment]
Just measuring the tree depth while searching for the address node gets you the netmask bitlength.
https://github.com/maxmind/MaxMind-DB-Reader-python/blob/master/maxminddb/reader.py#L127-L131
If you enumerate() that loop into a variable, that is your netmask. I'll try to do a PR.

**Comment by oschwald** [comment]
For reference, here is a similar [PR against the C# API](https://github.com/maxmind/MaxMind-DB-Reader-dotnet/pull/23/files) to get the prefix length when iterating over the search tree. A PR that doesn't break the API for existing users and has appropriate tests would likely be accepted.

**Comment by addrians** [comment]
The GeoIP2 models rely on dicts provided by the reader, so I thought of adding an extra key called "netmask". That should not have minimal impact on anything that reads dicts.
However, some test cases expect the get() function to return strings and I don't know what to do about that.
Here are my changes so far https://github.com/addrians/MaxMind-DB-Reader-python/commit/eb0cb7c339225eb4d29d547d973c9a47ac00ac59
Duplicating the get() function is a bad idea. Having a default parameter like netmask=False would be a step in the right direction.

**Comment by oschwald** [comment]
We should return the prefix length separately from the data that is returned. The data records in the database can contain arbitrary data structures with arbitrary keys. The format does not even require that there be a map. `get` could return a list, a string, a number, etc. I'd suggest adding a new method that returns the data and the prefix length and updating `get` to use this method.

**Comment by oschwald** [comment]
This is available in 1.5+ using the `get_with_prefix_len` method.
