### ISSUE TITLE
__int128 is not supported on this target

### ISSUE THREAD

**Issue by tiwilliam** [maxmind/MaxMind-DB-Reader-python#2]
Compilation of maxminddb.c fails on OS X Mavericks.

```
...
creating build
creating build/temp.macosx-10.9-intel-2.7
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c maxminddb.c -o build/temp.macosx-10.9-intel-2.7/maxminddb.o
clang: warning: argument unused during compilation: '-mno-fused-madd'
In file included from maxminddb.c:2:
/usr/local/include/maxminddb.h:64:18: error: __int128 is not supported on this target
typedef unsigned __int128 mmdb_uint128_t;
                 ^
1 error generated.
error: command 'cc' failed with exit status 1
```

**Comment by RR2DO2** [comment]
As per the previous referenced two bugs, the default setup with Homebrew is that you only get a 64 bit binary installed. Currently this means you will not be able to have 64 bit native code support for reading the database on OS X with the way the Python package builds/installs (it's universal or nothing). Other Python packages either dynamically load (which means running 32 bit Python causes a runtime error on importing the module) or handle it differently during install.

The MaxMind Python package probably should either only build the 64 bit native support when only that's available, or dynamically load the library. I haven't looked too closely at the code yet to see what makes sense.
