### ISSUE TITLE
Feature request: need a Writer in Python

### ISSUE THREAD

**Issue by jurisbu** [maxmind/MaxMind-DB-Reader-python#29]
Hello!

It is of-course great that Write is provided at all, not so great that it is implemented in Perl. Would be great to have a MaxMind DB writer in more current language like Python.

**Comment by oschwald** [comment]
We do not currently have plans to provide a MMDB writer in Python. However, much of the writer is written in C and creating a fork that used the Python C API (or any similar C-based interpreted language) would likely not be terribly difficult, if you are interested in working on that.

**Comment by jurisbu** [comment]
@oschwald Fair enough.

> However, much of the writer is written in C
Hmmm ... which project is that? Seems [libmaxminddb](https://github.com/maxmind/libmaxminddb) only provides reader.

**Comment by oschwald** [comment]
See [this file](https://github.com/maxmind/MaxMind-DB-Writer-perl/blob/master/c/tree.c), which is much of the code for the `MaxMind::DB::Writer` module.
