### ISSUE TITLE
Clarification around parsing `int32` from files

### ISSUE THREAD

**Issue by leesdolphin** [maxmind/MaxMind-DB-Reader-python#30]
I'm reviewing your code for a personal project and on [Line 109](https://github.com/maxmind/MaxMind-DB-Reader-python/blob/master/maxminddb/decoder.py#L109) of the decoder, you create a parser for `int32`.

It seems to indicate that the type can be shorter(from the `pad=True` parameter), however in the [actual function](https://github.com/maxmind/MaxMind-DB-Reader-python/blob/master/maxminddb/decoder.py#L53) it reads exactly 4 bytes(`type_size`) irrespective of the `size` passed in. This renders the `pad` option redundant.

My reading of the function implies line 53 should read `new_offset = offset + size`. Related to this it might also be wise to assert that `if pad: assert size <= type_size`.

**Comment by oschwald** [comment]
I think you may be right. A pull request would be welcomed. It would be nice to have a unit test for this. Re: the `assert`, we should throw an `InvalidDatabaseError` rather than an `AssertionError` in this case.

**Comment by leesdolphin** [comment]
I will put one together, and yeah I was intending for it to throw the `InvalidDatabaseError`, I just wanted to make the condition clear
