### ISSUE TITLE
Type hints for mypy

### ISSUE THREAD

**Issue by jolaf** [maxmind/MaxMind-DB-Reader-python#45]
I've created `.pyi` type hints (for Python 3) for this library and I would like to submit them to [`python/typeshed`](https://github.com/python/typeshed).
What do you think about it?

**Comment by txomon** [comment]
I would be very interested in this, what's the status?

**Comment by oschwald** [comment]
I apologize for not responding earlier, but having the type hints submitted there would be great!

**Comment by jolaf** [comment]
https://github.com/python/typeshed/pull/3245

**Comment by jolaf** [comment]
Could you please help with https://github.com/maxmind/GeoIP2-python/issues/70 too?

**Comment by oschwald** [comment]
One thing to note on the type hints, as of 1.5.0, `get` (and the new `get_with_prefix_len`) support `ipaddress.IPv4Address` and `ipaddress.IPv6Address` as arguments in addition to a string. See #48.

**Comment by jolaf** [comment]
In future when modifying the library API you can simultaneously update the stubs in `typeshed` via pull requests to https://github.com/python/typeshed/tree/master/third_party/3/maxminddb

**Comment by srittau** [comment]
Also, when and if you are committed to keeping the stubs updated yourself, you could consider shipping them with maxminddb. This way the stubs would always match the installed version and updated cause less friction. In that case, feel free to ping me to review the stubs or if you need assistance. But we are also happy to continue hosting the stubs in typeshed.

**Comment by oschwald** [comment]
Thanks!
