### ISSUE TITLE
Allow accessing the network field in the ASN mmdb file

### ISSUE THREAD

**Issue by darix** [maxmind/MaxMind-DB-Reader-python#57]
Follow up to https://github.com/maxmind/mod_maxminddb/issues/81 and https://github.com/maxmind/libmaxminddb/issues/207

**Comment by oschwald** [comment]
This is already possible using the `get_with_prefix_len` method.

**Comment by darix** [comment]
the API of the ruby client is a bit better. you don't have to manually construct the network address anymore. Is there any reason why the python interface is different?

**Comment by oschwald** [comment]
If you want a higher level library, I would suggest using `geoip2`. This exposed the network as an `ipaddress` object.

**Comment by darix** [comment]
Thank you will follow that route
