### ISSUE TITLE
ValueError: Unsupported open mode: MODE_MMAP_EXT

### ISSUE THREAD

**Issue by kirilb1** [maxmind/MaxMind-DB-Reader-python#64]
reader = maxminddb.open_database(self.GeoLite2_City_file, mode="MODE_MMAP_EXT")

Providing a mode to the open_database function results in the following error:

ValueError: Unsupported open mode: MODE_MMAP_EXT

**Comment by oschwald** [comment]
`MODE_MMAP_EXT` is a constant exported by `maxminddb`. You should not pass it in as a string. Try:

```python
reader = maxminddb.open_database(self.GeoLite2_City_file, maxminddb.MODE_MMAP_EXT)
```
