### ISSUE TITLE
New version is breaking Python 2 installs - missing setup.py python_requires update

### ISSUE THREAD

**Issue by scorchio** [maxmind/MaxMind-DB-Reader-python#69]
Hi,

The current version, which is stated to be Python 3 only, actually gets into Python 2 installations because of a missing python_requires update:

https://github.com/maxmind/MaxMind-DB-Reader-python/blob/30d8bf0b145ecff8f06542db403c08b97565b27a/setup.py#L112

Could you please fix this?

**Comment by gabor-boros** [comment]
Opening a PR in some minutes to fix this

**Comment by youtux** [comment]
Please consider [yanking](https://pypi.org/help/#yanked) the 1.0.0 release on PYPI.

**Comment by oschwald** [comment]
This should be resolved. Thanks for raising it.
