### ISSUE TITLE
Use ipv4 and ipv6 geographic libraries to generate mmdb files

### ISSUE THREAD

**Issue by ningliangquantil** [maxmind/MaxMind-DB-Reader-python#72]
Hi：

    When I only use the region library of ipv4 to generate a mmdb file, I found that some ipv4 cannot query the region information from mmdb. But when I use the region library of ipv6 and ipv4 to generate a mmdb file, I found that these ipv4 can find the corresponding Geographical location, what causes this. Is this normal？

Thanks！

**Comment by oschwald** [comment]
I am sorry; I don't understand the question. Perhaps you could provide code examples to show what you are seeing.
