### ISSUE TITLE
Running in an environment without mmap?

### ISSUE THREAD

**Issue by john-heasman-cg** [maxmind/MaxMind-DB-Reader-python#76]
Is there a way to run this is in an environment without mmap any more, given that decoder.py requires it?

**Comment by oschwald** [comment]
It should work. Are you getting a particular error?

**Comment by john-heasman-cg** [comment]
Some more context: I am running this in Splunk and getting:

10-15-2020 23:26:29.811 ERROR ChunkedExternProcessor - stderr:     from mmap import mmap
10-15-2020 23:26:29.811 ERROR ChunkedExternProcessor - stderr: ModuleNotFoundError: No module named 'mmap'

I've found a few posts on Splunk forums with people pointing out that mmap is not present in Splunk's python (e.g. https://community.splunk.com/t5/All-Apps-and-Add-ons/how-can-I-enable-MMAP-caching-in-Google-GeoIP-of-MaxMind/m-p/33754)

I am hoping to avoid solution that involve distributing the .so with my app. I noticed that 1.5.4 of decoder.py did not use mmap.

**Comment by oschwald** [comment]
Ah, I see what happened. We accidentally introduced an unchecked import when dropping Python 2 support. It should be easy enough to remove that. Thanks for reporting.

**Comment by oschwald** [comment]
2.0.3 has been released with a fix for this. Thanks!

**Comment by john-heasman-cg** [comment]
Thanks for the incredibly fast turn around!
